objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    padm_api:
      description: Make an HTTP request to a PADM API
      name: padm_api
      namespace: ''
      version_added: 1.0.0
    padm_snmp_user:
      description: Manages SNMP users for a Tripplite Poweralert device
      name: padm_snmp_user
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.0.1
