---
- hosts: "{{ poweralert_host }}"
  connection: local
  gather_facts: false

  vars:
    # Create an anchor for hostname and login info
    tripplite_info: &tripplite_info
      poweralert_endpoint: "{{ poweralert_host_fqdn }}"
      username: "{{ tripplite_user }}"
      password: "{{ tripplite_pass }}"

  tasks:
  - name: Reboot poweralert device
    tripplite.poweralert.padm_api:
      <<: *tripplite_info
      uri: /api/system_reboot
      method: post
    register: tripplite_info
    delegate_to: localhost

  - name: Show response
    debug:
      msg: "{{ tripplite_info }}"